# name: sphinx documentation

# on: [push, pull_request, workflow_dispatch]

# permissions:
#   contents: write

# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v3
#       - name: Install dependencies
#         run: |
#           pip install sphinx sphinx_rtd_theme myst_parser
#       - name: Sphinx build
#         run: |
#           sphinx-build sphinx_docs sphinx_docs/_build
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.event_name == 'push' }}
#         with:
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: _build
#           force_orphan: true

name: Build and Deploy Documentation

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Build Documentation
        run: |
          cd docs
          make html

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
